### ISSUE TITLE
dnu restore fails on MusicStore build

### ISSUE THREAD

**Issue by codespare** [aspnet/DnxTools#12]
dnu restore gets lost recursing down node_modules directories I think
```
PS [dev] C:\User\Dev\ext\Universe\MusicStore>.\build.cmd
Attempting to gather dependencies information for package 'KoreBuild.0.2.1-rc1-15542' with respect to project 'packages', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'KoreBuild.0.2.1-rc1-15542' with DependencyBehavior 'Lowest'
Resolving actions to install package 'KoreBuild.0.2.1-rc1-15542'
Resolved actions to install package 'KoreBuild.0.2.1-rc1-15542'
Adding package 'KoreBuild.0.2.1-rc1-15542' to folder 'packages'
Added package 'KoreBuild.0.2.1-rc1-15542' to folder 'packages'
Successfully installed 'KoreBuild 0.2.1-rc1-15542' to packages
Attempting to gather dependencies information for package 'Sake.0.2.2' with respect to project 'packages', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'Sake.0.2.2' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Sake.0.2.2'
Resolved actions to install package 'Sake.0.2.2'
Adding package 'Sake.0.2.2' to folder 'packages'
Added package 'Sake.0.2.2' to folder 'packages'
Successfully installed 'Sake 0.2.2' to packages
Determining latest version
'dnx-clr-win-x86.1.0.0-rc1-15844' is already installed in c:\Users\User\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-15844.
Adding c:\Users\User\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-15844\bin to process PATH
Adding c:\Users\User\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-15844\bin to user PATH
Updating alias 'default' to 'dnx-clr-win-x86.1.0.0-rc1-15844'
'dnx-coreclr-win-x86.1.0.0-rc1-15844' is already installed in c:\Users\User\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc1-15844.
Adding c:\Users\User\.dnx\runtimes\dnx-coreclr-win-x86.1.0.0-rc1-15844\bin to process PATH
'dnx-clr-win-x64.1.0.0-rc1-15844' is already installed in c:\Users\User\.dnx\runtimes\dnx-clr-win-x64.1.0.0-rc1-15844.
Adding c:\Users\User\.dnx\runtimes\dnx-clr-win-x64.1.0.0-rc1-15844\bin to process PATH
'dnx-coreclr-win-x64.1.0.0-rc1-15844' is already installed in c:\Users\User\.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-rc1-15844.
Adding c:\Users\User\.dnx\runtimes\dnx-coreclr-win-x64.1.0.0-rc1-15844\bin to process PATH
Adding c:\Users\User\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-15844\bin to process PATH
info: Build v2: False
info: Exec
info:   program: cmd
info:   commandline: /C dnu restore --parallel
info:   workingdir: C:\Dam\Dev\ext\Universe\MusicStore
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-15844

----------
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateDirectories(String path)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.CollectProjectFiles(String directory, List`1 results)
   at Microsoft.Dnx.Tooling.RestoreProjectsCollector.Find(String restoreDirectory, IEnumerable`1& projectJsonFiles)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
fail: Exit code 1 from cmd
fail: Stack trace:
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.<RenderViewLevel0>b__9f() in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 8837
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.StartingTarget(String name) in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 1937
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.<RenderViewLevel0>b__5e() in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 3112
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.StartingTarget(String name) in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 1937
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.<RenderViewLevel0>b__5f() in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 3129
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.StartingTarget(String name) in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 1937
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.<RenderViewLevel0>b__60() in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 3146
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.StartingTarget(String name) in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 1937
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.<RenderViewLevel0>b__61() in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 3163
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Viewf4002438f8ae4f6f8b7eb68e18e9a133.<RenderViewLevel0>b__59() in c:\Users\User\AppData\Local\Temp\218894c96a1e4b568904f1a85e0e8e47-1.cs:line 3019
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)
```

**Comment by Eilon** [comment]
Can you open this bug in the DNX issue tracker? https://github.com/aspnet/dnx/issues

This repo is for some build tools, not DNX/DNU.
